; NX-ISD PIO configuration file

[env:4d_systems_esp32s3_gen4_r8n16]
platform = espressif32@6.6.0
platform_packages =
    platformio/tool-esptoolpy@~2.41100.0
board = 4d_systems_esp32s3_gen4_r8n16
framework = arduino
monitor_speed = 115200
upload_port = COM17
monitor_port = COM17
build_flags =
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1
    -D BOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
lib_deps =
    lovyan03/LovyanGFX
    adafruit/Adafruit NeoPixel
    adafruit/Adafruit BNO08x
    boschsensortec/BME68x Sensor library
    closedcube/ClosedCube OPT3001
    sparkfun/SparkFun MAX3010x Pulse and Proximity Sensor Library
    adafruit/Adafruit MAX1704X
    constiko/RTC RV-3028-C7 Arduino Library